apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dongle-test.fullname" . }}-test-configmap
  namespace: {{ .Release.Namespace }}
data:
  test: "why"
  nginx.tmpl: {{ .Values.astagNginxTemplate }}
