apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dongle-test.fullname" . }}-test-configmap
  namespace: {{ .Release.Namespace }}
data:
  nginx.tmpl: |-
{{ .Files.Get "templates/nginx.tmpl" | nindent 4 }}