apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dongle-test.fullname" . }}-test-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- if eq .Values.env "stag" -}}
  nginx.tmpl: {{ .Values.stagNginxTemplate | quote }}
  {{- else -}}
  nginx.tmpl: {{ .Values.prodNginxTemplate | quote }}
  {{- end -}}
