apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dongle-test.fullname" . }}-test-configmap
  namespace: {{ .Release.Namespace }}
data:
  test: "test"
  nginx.tmpl: {{ file.Read "./templates/nginx.tmpl" | toJSON }}