nodeclass:
  name: al2
  amiFamily: AL2
  # You must replace 'clusterName'.
  clusterName: dongle

nodepools:
  - name: multi-arch-general
    requirements:
     - key: karpenter.k8s.aws/instance-category
       operator: In
       values: ["t", "c", "m"]
     - key: kubernetes.io/arch
       operator: In
       values: ["amd64", "arm64"]
     - key: karpenter.k8s.aws/instance-size
       operator: In
       values: ["medium", "large", "xlarge"]
     - key: karpenter.sh/capacity-type
       operator: In
       values: ["on-demand"]
    limits:
      cpu: 30
      memory: 64Gi
  
disruption:
  consolidationPolicy: WhenEmpty
  consolidateAfter: 30s